name: execute Python additional

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Test  # Only this part is written by me remaing part is from document https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python :)
        run: |
             python additional.py
    