name: execute Python additional

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependebcy
        run: |
             python -m pip install --upgrade pip
             pip install pytest

      - name: Run Test
        run: |
             python -m pytest additional.py
    
